name: Dependency Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  dependency_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Dependency Review
      uses: actions/dependency-review-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        check-runs: dependency-check
        # You can specify additional configuration options here if needed

    - name: Check Status Checks
      run: |
        status_checks="dependency-check"
        for check in $status_checks; do
          status=$(curl -s -u ${{ secrets.GITHUB_ACTOR }}:$GITHUB_TOKEN \
            -H "Accept: application/vnd.github.antiope-preview+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/check-runs?check_name=$check" \
            | jq -r .total_count)
          if [[ $status -eq 0 ]]; then
            echo "Dependency Review check '$check' has not passed."
            exit 1
          fi
        done

  # Add more steps for your build and tests if needed

